#' Need A Title For This Function
#'
#' Performs weighted smooth regression for a given lambda1, lambda2 combination.
#' 
#' @param data An object of class "WTsth.data" as generated by prep()
#' @param lambda1 A numeric vector. Lambda_1 values to be considered. Provided
#'   values will be transformed to 2^(lambda1).
#' @param lambda2 A numeric vector Lambda_2 values to be considered. Provided
#'   values will be transformed to 2^(lambda2).
#' @param family A character. The family of the outcome. Must be one of
#'   "gaussian" (Y is continuous) or "binomial" (Y is binary).
#' @param cv.control A list object. Allows user to control cross-validation
#'   procedure. Allowed elements are "n.fold", the number of cross-validation
#'   folds; "n.core", the number of cores to use in procedure; and
#'   "stratified", if TRUE and family = "binomial", the folds will be
#'   stratified (this option should be used if either category is
#'   "rare.")
#' @param iter.control A list object. Allows user to control iterative
#'   update procedure. Allowed elements are "max.iter", the maximum number
#'   of iterations; "tol.beta", the difference between consecutive beta
#'   updates below which the procedure is deemed converged; and "tol.loss",
#'   the difference in consecutive loss updates below which the procedure
#'   is deemed converged.
#'
#' @examples
#' 
#' # we need to create a data set and add an example
#' 
#' @returns A numeric vector. The estimated model parameters
#' 
#'
#' @include ctnsSolution.R helpful_tests.R rwlsSolution.R utils.R
#'
#' @export
fit_WTSMTH <- function(data, lambda1, lambda2,
                       family = c("gaussian", "binomial"), 
                       iter.control = list(max_iter = 8L, 
                                           tol_beta = 10^(-3), 
                                           tol_loss = 10^(-6)),
                       ...) {
  
  extras <- list(...)
  
  # take the first value as default
  family <- match.arg(family)
  
  stopifnot(
    "`data` must be a 'WTsth.data' object" = !missing(data) && inherits(data, "WTsth.data"),
    "`lambda1 must be a numeric vector" = !missing(lambda1) && .isNumericVector(lambda1),
    "`lambda2 must be a numeric vector" = !missing(lambda2) && .isNumericVector(lambda2),
    "`iter.control` must be a list; allowed elements are max.iter, tol.beta, and tol.loss" = 
      .isNamedList(iter.control, c("max.iter", "tol.beta", "tol.loss")),
  )
  
  iter.control <- .testIterControl(iter.control)  

  if (family == "binomial") data$Y <- .confirmBinary(data$Y)
  
  if (is.null(data$XZ)) data <- .expandWTsmth(data)
  
  if (!is.null(extras$subset)) {
    data$Y <- data$Y[subset]
    data$XZ <- data$XZ[subset, ]
  }

  X_app <- cbind(0.0, sqrt(2.0^lambda2) * data$A)
  rownames(X_app) <- rownames(data$A)
  Y_app <- rep.int(0L, nrow(data$A))
  names(Y_app) <- rownames(data$A)
  
  if (family == "gaussian") {
    .ctnsSolution(data = data, X.app = X_app, Y.app = Y_app, lambda1 = lambda1)
  } else {
    .rwlsSolution(data = data,
                  X.app = X_app, Y.app = Y_app, 
                  lambda1 = lambda1,
                  iter.control = iter.control)
  }
}
